# Generated by Django 5.2.6 on 2025-10-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='certification_level',
            field=models.CharField(blank=True, choices=[('bachelor', 'Licence'), ('master', 'Master'), ('phd', 'Doctorat'), ('certified', 'Certifié'), ('other', 'Autre')], default='bachelor', max_length=100, verbose_name='Niveau de certification'),
        ),
    ]
