# Generated by Django 5.2.6 on 2025-10-25 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_teacher_certification_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.teacher', verbose_name='Enseignant assigné'),
        ),
        migrations.AddField(
            model_name='student',
            name='auto_generated_username',
            field=models.BooleanField(default=False, verbose_name="Nom d'utilisateur généré automatiquement"),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_id',
            field=models.CharField(blank=True, help_text="Code d'invitation ou identifiant de l'école", max_length=50, null=True, verbose_name='Identifiant scolaire'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='auto_generated_username',
            field=models.BooleanField(default=False, verbose_name="Nom d'utilisateur généré automatiquement"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'école"),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Token de vérification email'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email vérifié'),
        ),
    ]
