# Generated by Django 5.2.6 on 2025-10-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_add_enhanced_registration_fields'),
        ('students', '0003_alter_student_birth_date'),
    ]

    operations = [
    ]
