# Generated by Django 5.2.6 on 2025-10-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="last_daily_reward",
            field=models.DateField(
                blank=True, null=True, verbose_name="Dernière récompense quotidienne"
            ),
        ),
    ]
