# Generated by Django 5.2.6 on 2025-10-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_merge_20251026_1526'),
        ('students', '0004_student_last_daily_reward'),
    ]

    operations = [
    ]
