# Generated by Django 5.2.6 on 2025-10-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0002_accessory_mission_alter_badge_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AddField(
            model_name="avatar",
            name="name",
            field=models.CharField(
                default="Mon Avatar", max_length=100, verbose_name="Nom de l'avatar"
            ),
        ),
    ]
