# Generated by Django 5.2.6 on 2025-10-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_add_avatar_name_and_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
