# EduKids - Docker Compose Configuration
# Services nécessaires : PostgreSQL, Redis

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: edukids_postgres
    environment:
      POSTGRES_DB: edukids_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: edukids_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Cache et Queue Redis
  redis:
    image: redis:7-alpine
    container_name: edukids_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin pour gérer PostgreSQL (optionnel)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: edukids_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@edukids.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  default:
    name: edukids_network
