# Generated by Django 5.2.6 on 2025-10-25 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_badge_story_storyprogress_studentbadge'),
        ('students', '0003_alter_student_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('enchanted_storybook', 'Enchanted Storybook'), ('adventure_scroll', 'Adventure Scroll'), ('fantasy_narrator', 'Fantasy Narrator'), ('imagination_explorer', 'Imagination Explorer'), ('story_explorer', 'Story Explorer'), ('super_reader', 'Super Reader'), ('perfect_score', 'Perfect Score'), ('speed_reader', 'Speed Reader'), ('theme_master', 'Theme Master'), ('curious_mind', 'Curious Mind'), ('consistent_learner', 'Consistent Learner')], max_length=30, unique=True, verbose_name='Badge Type'),
        ),
        migrations.CreateModel(
            name='StoryAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_story', models.TextField(help_text="The child's original story text", verbose_name='Original Story')),
                ('corrected_story', models.TextField(help_text='AI-corrected version with grammar and spelling fixes', verbose_name='Corrected Story')),
                ('feedback', models.TextField(help_text='Encouraging feedback from AI', verbose_name='AI Feedback')),
                ('questions', models.JSONField(help_text='3 comprehension/reflection questions', verbose_name='Reflection Questions')),
                ('badge', models.CharField(choices=[('enchanted_storybook', 'Enchanted Storybook'), ('adventure_scroll', 'Adventure Scroll'), ('fantasy_narrator', 'Fantasy Narrator'), ('imagination_explorer', 'Imagination Explorer')], max_length=30, verbose_name='Badge Earned')),
                ('creativity_score', models.IntegerField(default=0, help_text='AI-assessed creativity level', verbose_name='Creativity Score (0-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_assessments', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Story Assessment',
                'verbose_name_plural': 'Story Assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
