# Generated by Django 5.2.6 on 2025-10-26 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_add_story_writing_badges'),
        ('students', '0003_alter_student_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Character Name')),
                ('image', models.ImageField(upload_to='characters/%Y/%m/', verbose_name='Drawing Image')),
                ('ai_version', models.ImageField(blank=True, null=True, upload_to='characters/ai/%Y/%m/', verbose_name='AI Enhanced Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_drawings', to='assessments.story', verbose_name='Linked Story')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_drawings', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Character Drawing',
                'verbose_name_plural': 'Character Drawings',
                'ordering': ['-created_at'],
            },
        ),
    ]
