# Generated by Django 5.2.6 on 2025-10-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_characterdrawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, help_text='Custom badge image (optional, uses icon if not provided)', null=True, upload_to='badges/', verbose_name='Badge Image'),
        ),
    ]
