# Generated by Django 5.2.6 on 2025-10-13 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('category', models.CharField(choices=[('general', 'Général'), ('francais', 'Français'), ('mathematiques', 'Mathématiques'), ('sciences', 'Sciences'), ('histoire', 'Histoire'), ('geographie', 'Géographie'), ('other', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('keywords', models.JSONField(default=list, help_text='Mots-clés pour la recherche sémantique', verbose_name='Mots-clés')),
                ('grade_levels', models.JSONField(default=list, help_text='CP, CE1, CE2, CM1, CM2', verbose_name='Niveaux')),
                ('usage_count', models.IntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Base de connaissances',
                'verbose_name_plural': 'Base de connaissances',
                'ordering': ['-usage_count', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VirtualAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'assistant")),
                ('personality', models.CharField(default='friendly', help_text='friendly, professional, playful, etc.', max_length=50, verbose_name='Personnalité')),
                ('language', models.CharField(default='fr', max_length=10, verbose_name='Langue')),
                ('welcome_message', models.TextField(default="Bonjour! Je suis là pour t'aider dans ton apprentissage. Comment puis-je t'aider aujourd'hui?", verbose_name='Message de bienvenue')),
                ('system_prompt', models.TextField(help_text="Instructions pour l'IA", verbose_name='Prompt système')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Assistant Virtuel',
                'verbose_name_plural': 'Assistants Virtuels',
            },
        ),
        migrations.CreateModel(
            name='AssistantInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name="Question de l'élève")),
                ('answer', models.TextField(verbose_name="Réponse de l'assistant")),
                ('was_helpful', models.BooleanField(blank=True, null=True, verbose_name='Réponse utile?')),
                ('feedback', models.TextField(blank=True, verbose_name="Feedback de l'élève")),
                ('context', models.JSONField(default=dict, help_text='Informations contextuelles', verbose_name='Contexte')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='Temps de réponse (secondes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_interactions', to='students.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Interaction Assistant',
                'verbose_name_plural': 'Interactions Assistant',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Généré automatiquement à partir du premier message', max_length=200, verbose_name='Titre')),
                ('context', models.JSONField(default=dict, help_text="Informations contextuelles pour l'IA", verbose_name='Contexte')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Démarrée le')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminée le')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='students.student', verbose_name='Élève')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='assistant.virtualassistant', verbose_name='Assistant')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('student', 'Élève'), ('assistant', 'Assistant'), ('system', 'Système')], max_length=10, verbose_name='Émetteur')),
                ('message_type', models.CharField(choices=[('text', 'Texte'), ('audio', 'Audio'), ('image', 'Image'), ('system', 'Système')], default='text', max_length=10, verbose_name='Type de message')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('file', models.FileField(blank=True, null=True, upload_to='messages/', verbose_name='Fichier joint')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires (tokens, modèle IA, etc.)', verbose_name='Métadonnées')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['conversation', 'created_at'],
            },
        ),
    ]
