# Generated by Django 5.2.6 on 2025-10-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="topic",
            field=models.CharField(
                choices=[
                    ("general", "Général"),
                    ("francais", "Français"),
                    ("mathematiques", "Mathématiques"),
                    ("sciences", "Sciences"),
                    ("histoire", "Histoire"),
                    ("geographie", "Géographie"),
                    ("other", "Autre"),
                ],
                default="general",
                max_length=20,
                verbose_name="Sujet",
            ),
        ),
    ]
