# Generated by Django 5.2.6 on 2025-10-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0004_quizattempt_quizattemptanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattemptanswer",
            name="selected_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
