# Generated by Django 5.2.6 on 2025-10-13 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la matière')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône (ex: fa-book)", max_length=50, verbose_name='Icône')),
                ('color', models.CharField(default='#3498db', help_text='Code couleur hex (ex: #3498db)', max_length=7, verbose_name='Couleur')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('exercise_type', models.CharField(choices=[('qcm', 'QCM'), ('vrai_faux', 'Vrai/Faux'), ('text_field', 'Texte à trous'), ('dictee', 'Dictée'), ('problem', 'Problème mathématique'), ('conjugaison', 'Conjugaison'), ('calcul', 'Calcul'), ('lecture', 'Compréhension de lecture'), ('grammaire', 'Grammaire'), ('orthographe', 'Orthographe')], max_length=20, verbose_name="Type d'exercice")),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Très facile'), (2, 'Facile'), (3, 'Moyen'), (4, 'Difficile'), (5, 'Très difficile')], default=3, verbose_name='Niveau de difficulté')),
                ('estimated_time', models.IntegerField(default=10, verbose_name='Temps estimé (minutes)')),
                ('points', models.IntegerField(default=10, verbose_name='Points')),
                ('instructions', models.TextField(verbose_name='Consignes')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercises', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question')),
                ('question_type', models.CharField(choices=[('single_choice', 'Choix unique'), ('multiple_choice', 'Choix multiple'), ('text', 'Texte libre'), ('number', 'Nombre'), ('true_false', 'Vrai/Faux')], max_length=20, verbose_name='Type de question')),
                ('points', models.IntegerField(default=1, verbose_name='Points')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('hint', models.TextField(blank=True, verbose_name='Indice')),
                ('explanation', models.TextField(blank=True, verbose_name='Explication')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exercises.exercise', verbose_name='Exercice')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['exercise', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500, verbose_name='Réponse')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Réponse correcte')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('explanation', models.TextField(blank=True, verbose_name='Explication')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exercises.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ContentLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('audio', 'Audio'), ('pdf', 'PDF'), ('text', 'Texte')], max_length=10, verbose_name='Type de contenu')),
                ('file', models.FileField(blank=True, null=True, upload_to='library/', verbose_name='Fichier')),
                ('url', models.URLField(blank=True, verbose_name='URL externe')),
                ('grade_levels', models.JSONField(default=list, help_text='Liste des niveaux: CP, CE1, CE2, CM1, CM2', verbose_name='Niveaux concernés')),
                ('tags', models.JSONField(default=list, verbose_name='Mots-clés')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_content', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='exercises.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Bibliothèque de ressources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du thème')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('grade_level', models.CharField(choices=[('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2')], max_length=3, verbose_name='Niveau')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='exercises.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Thème',
                'verbose_name_plural': 'Thèmes',
                'ordering': ['subject', 'grade_level', 'order'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.topic', verbose_name='Thème'),
        ),
    ]
