# Generated by Django 5.2.6 on 2025-10-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="subjects/", verbose_name="Image"
            ),
        ),
    ]
