# Generated by Django 5.2.6 on 2025-10-20 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_subject_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "ordering": ["order"],
                "verbose_name": "Réponse",
                "verbose_name_plural": "Réponses",
            },
        ),
        migrations.AlterModelOptions(
            name="contentlibrary",
            options={
                "verbose_name": "Bibliothèque de contenu",
                "verbose_name_plural": "Bibliothèques de contenu",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["order"],
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Thème",
                "verbose_name_plural": "Thèmes",
            },
        ),
        migrations.RemoveField(
            model_name="contentlibrary",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="contentlibrary",
            name="description",
        ),
        migrations.RemoveField(
            model_name="contentlibrary",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="contentlibrary",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="contentlibrary",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="contentlibrary",
            name="url",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="difficulty_level",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="estimated_time",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="title",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="question",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="question",
            name="explanation",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="created_at",
        ),
        migrations.AddField(
            model_name="contentlibrary",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AddField(
            model_name="exercise",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créateur",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("facile", "Facile"),
                    ("moyen", "Moyen"),
                    ("difficile", "Difficile"),
                ],
                default="facile",
                max_length=10,
                verbose_name="Difficulté",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exercise",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AddField(
            model_name="exercise",
            name="name",
            field=models.CharField(
                default="Default Exercice",
                max_length=200,
                verbose_name="Nom de l'exercice",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exercise",
            name="time_limit",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Temps limite (minutes)"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer_text",
            field=models.TextField(verbose_name="Texte de la réponse"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="contentlibrary",
            name="content_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Vidéo"), ("audio", "Audio")],
                max_length=10,
                verbose_name="Type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="contentlibrary",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="content/", verbose_name="Fichier"
            ),
        ),
        migrations.AlterField(
            model_name="contentlibrary",
            name="grade_levels",
            field=models.JSONField(default=list, verbose_name="Niveaux scolaires"),
        ),
        migrations.AlterField(
            model_name="contentlibrary",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_library",
                to="exercises.subject",
                verbose_name="Matière",
            ),
        ),
        migrations.AlterField(
            model_name="contentlibrary",
            name="tags",
            field=models.JSONField(default=list, verbose_name="Tags"),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("QCM", "QCM"),
                    ("dictée", "Dictée"),
                    ("trous", "Texte à trous"),
                    ("math", "Problème mathématique"),
                ],
                max_length=20,
                verbose_name="Type d'exercice",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="instructions",
            field=models.TextField(blank=True, verbose_name="Instructions"),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="points",
            field=models.PositiveIntegerField(default=10, verbose_name="Points"),
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="question",
            name="points",
            field=models.PositiveIntegerField(default=1, verbose_name="Points"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(verbose_name="Texte de la question"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("text", "Texte"), ("image", "Image"), ("audio", "Audio")],
                default="text",
                max_length=10,
                verbose_name="Type de question",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="grade_level",
            field=models.CharField(
                choices=[
                    ("CP", "CP"),
                    ("CE1", "CE1"),
                    ("CE2", "CE2"),
                    ("CM1", "CM1"),
                    ("CM2", "CM2"),
                ],
                max_length=3,
                verbose_name="Niveau scolaire",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre"),
        ),
    ]
