# Generated by Django 5.2.6 on 2025-10-20 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exercises",
            "0003_alter_answer_options_alter_contentlibrary_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre de la leçon"),
                ),
                ("content", models.TextField(verbose_name="Contenu de la leçon")),
                (
                    "media",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="lessons/",
                        verbose_name="Média (image/vidéo)",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="exercises.topic",
                        verbose_name="Thème",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leçon",
                "verbose_name_plural": "Leçons",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
