# Generated by Django 5.2.6 on 2025-10-21 11:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0005_question_creator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "completed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("score", models.FloatField()),
                ("total_points", models.IntegerField()),
                ("earned_points", models.IntegerField()),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="exercises.exercise",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat d'exercice",
                "verbose_name_plural": "Résultats d'exercices",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_answer", models.TextField()),
                ("is_correct", models.BooleanField()),
                ("points_earned", models.IntegerField()),
                (
                    "exercise_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exercises.exerciseresult",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse d'étudiant",
                "verbose_name_plural": "Réponses d'étudiants",
            },
        ),
    ]
