# Generated by Django 5.2.6 on 2025-10-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0006_exerciseresult_studentanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("QCM", "QCM"),
                    ("dictée", "Dictée"),
                    ("texte_à_trous", "Texte à trous"),
                    ("math", "Problème mathématique"),
                ],
                max_length=20,
                verbose_name="Type d'exercice",
            ),
        ),
    ]
