# Generated by Django 5.2.6 on 2025-10-21 18:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0008_classroom_assignment_classroommembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="exercise",
        ),
        migrations.AddField(
            model_name="assignment",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("QCM", "QCM"),
                    ("dictée", "Dictée"),
                    ("texte_à_trous", "Texte à trous"),
                ],
                default="QCM",
                max_length=20,
                verbose_name="Type de devoir",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignment",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("facile", "Facile"),
                    ("moyen", "Moyen"),
                    ("difficile", "Difficile"),
                ],
                default="moyen",
                max_length=10,
                verbose_name="Difficulté",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignment",
            name="points",
            field=models.PositiveIntegerField(default=10, verbose_name="Points"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="time_limit",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Temps limite (minutes)"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="title",
            field=models.CharField(
                default="Devoir sans titre",
                max_length=200,
                verbose_name="Titre du devoir",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="AssignmentQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(verbose_name="Texte de la question"),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=1, verbose_name="Points"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("hint", models.TextField(blank=True, verbose_name="Indice")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="assignment_questions/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exercises.assignment",
                        verbose_name="Devoir",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question de devoir",
                "verbose_name_plural": "Questions de devoirs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(verbose_name="Texte de la réponse")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Réponse correcte"),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, verbose_name="Explication"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exercises.assignmentquestion",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse de devoir",
                "verbose_name_plural": "Réponses de devoirs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "completed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("score", models.FloatField()),
                ("total_points", models.IntegerField()),
                ("earned_points", models.IntegerField()),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="exercises.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat de devoir",
                "verbose_name_plural": "Résultats de devoirs",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentStudentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_answer", models.TextField()),
                ("is_correct", models.BooleanField()),
                ("points_earned", models.IntegerField()),
                (
                    "assignment_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exercises.assignmentresult",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.assignmentquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse d'étudiant au devoir",
                "verbose_name_plural": "Réponses d'étudiants aux devoirs",
            },
        ),
    ]
