# Generated by Django 5.2.6 on 2025-10-21 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0009_remove_assignment_exercise_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentquestion",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="assignmentresult",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="assignmentanswer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="assignmentstudentanswer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="assignmentresult",
            name="student",
        ),
        migrations.RemoveField(
            model_name="assignmentstudentanswer",
            name="assignment_result",
        ),
        
        migrations.CreateModel(
            name="SubjectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="exercises.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adhésion à une matière",
                "verbose_name_plural": "Adhésions aux matières",
                "unique_together": {("subject", "student")},
            },
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
        migrations.DeleteModel(
            name="AssignmentAnswer",
        ),
        migrations.DeleteModel(
            name="AssignmentQuestion",
        ),
        migrations.DeleteModel(
            name="AssignmentResult",
        ),
        migrations.DeleteModel(
            name="AssignmentStudentAnswer",
        ),
        migrations.DeleteModel(
            name="Classroom",
        ),
        migrations.DeleteModel(
            name="ClassroomMembership",
        ),
    ]
