# Generated by Django 5.2.6 on 2025-10-21 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0010_remove_assignmentquestion_assignment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="created_by",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_subjects",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="grade_level",
            field=models.CharField(
                choices=[
                    ("CP", "CP"),
                    ("CE1", "CE1"),
                    ("CE2", "CE2"),
                    ("CM1", "CM1"),
                    ("CM2", "CM2"),
                ],
                default="CP",
                help_text="Niveau scolaire pour cette matière/classe",
                max_length=10,
            ),
        ),
    ]
