# Generated by Django 5.2.6 on 2025-10-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0011_subject_created_by_subject_grade_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="available_from",
            field=models.DateTimeField(
                blank=True,
                help_text="When this exercise becomes available as an assignment (optional)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Due date for this assignment (optional)",
                null=True,
            ),
        ),
    ]
